Automated build.

diff --git a/.github/workflows/docker-apptainer-build-push.yml b/.github/workflows/docker-apptainer-build-push.yml
--- a/.github/workflows/docker-apptainer-build-push.yml
+++ b/.github/workflows/docker-apptainer-build-push.yml
@@ -1,92 +1,149 @@
-name: Docker and Apptainer Build and Push
+#!/bin/bash
 
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+set -e
 
-jobs:
+# a function to install apt packages only if they are not installed
+function apt_install() {
+    if ! dpkg -s "$@" >/dev/null 2>&1; then
+        if [ "$(find /var/lib/apt/lists/* | wc -l)" = "0" ]; then
+            apt-get update
+        fi
+        apt-get install -y --no-install-recommends "$@"
+    fi
+}
 
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - 
-        name: Set the environment variables
-        run: echo "NOW=$( date '+%F-%H%M%S%2N' )" >> $GITHUB_ENV
-      -
-        name: Checkout 
-        uses: actions/checkout@v3
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      -
-        name: Docker build and push
-        uses: docker/build-push-action@v4.0.0
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:${{ env.NOW }}
-      -
-        name: Set up Apptainer
-        uses: eWaterCycle/setup-apptainer@v2
-        with:
-          apptainer-version: 1.1.9
-      -
-        name: Build Apptainer container
-        run: apptainer build ${{ secrets.DOCKER_HUB_CONTAINER }}.sif docker://${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CONTAINER }}:${{ env.NOW }}
-      -
-        name: Run Apptainer container
-        run: |
-          apptainer run ${{ secrets.DOCKER_HUB_CONTAINER }}.sif cat /etc/os-release
-          apptainer run ${{ secrets.DOCKER_HUB_CONTAINER }}.sif cat /home/rstudio/project-dir/.GHSHAMSG > release.txt
-      -
-        name: Upload Singularity Image File
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ secrets.DOCKER_HUB_CONTAINER }}.sif
-          path: ./${{ secrets.DOCKER_HUB_CONTAINER }}.sif
-      -
-        name: Download artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: ${{ secrets.DOCKER_HUB_CONTAINER }}.sif
-      -
-        name: Test artifact download
-        run: ls -R
-      -
-        name: Zip artifact
-        uses: thedoctor0/zip-release@0.7.1
-        with:
-          filename: ${{ secrets.DOCKER_HUB_CONTAINER }}.zip
-          exclusions: '*.git* *.md *.txt Dockerfile /src/*'
-      - 
-        name: Create GitHub release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ env.NOW }}
-          release_name: sif-${{ env.NOW }}
-          body_path: ./release.txt
-          draft: false
-          prerelease: false
-      - 
-        name: Upload release asset
-        id: upload-release-asset 
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./${{ secrets.DOCKER_HUB_CONTAINER }}.zip
-          asset_name: sif-${{ env.NOW }}.zip
-          asset_content_type: application/zip
+# personal
+
+apt_install           \
+    wget              \
+    parallel          \
+    vim               \
+    nnn               \
+    tmux              \
+    curl              \
+    less              \
+    bat               \
+    rsync             \
+    openssh-server    \
+    neofetch
+
+# dep.sh
+
+apt_install                \
+    libcurl4-openssl-dev   \
+    libharfbuzz-dev        \
+    libfribidi-dev         \
+    libfontconfig1-dev     \
+    build-essential        \
+    cmake                  \
+    libopenblas-dev        \
+    liblapack-dev          \
+    libarpack2-dev         \
+    libsuperlu-dev         \
+    libgsl-dev             \
+    libarmadillo-dev       \
+    libeigen3-dev
+
+R -e "                     \
+    install.packages(      \
+        c(                 \
+          'car',           \
+          'deSolve',       \
+          'devtools',      \
+          'fda',           \
+          'fds',           \
+          'ggplot2',       \
+          'knitr',         \
+          'latex2exp',     \
+          'magrittr',      \
+          'MASS',          \
+          'Matrix',        \
+          'mice',          \
+          'numDeriv',      \
+          'plyr',          \
+          'Rcpp',          \
+          'RcppArmadillo', \
+          'RcppGSL',       \
+          'Rdpack',        \
+          'remotes',       \
+          'reshape2',      \
+          'rmarkdown',     \
+          'roxygen2',      \
+          'Ryacas',        \
+          'stringi',       \
+          'testthat',      \
+          'tibble',        \
+          'tinytex',       \
+          'xtable'         \
+        ),                 \
+        repos = 'https://packagemanager.rstudio.com/all/__linux__/jammy/latest', \
+        lib = file.path(Sys.getenv('R_HOME'), 'library')                         \
+    )                                                                            \
+"
+
+R -e "                                                    \
+    remotes::install_version(                             \
+        package = 'roxygen2',                             \
+        version = '5.0.1',                                \
+        repos = c(CRAN = 'https://cran.rstudio.com'),     \
+        lib = file.path(Sys.getenv('R_HOME'), 'library')  \
+    )                                                     \
+"
+
+R -e "                                                    \
+    try(tinytex::install_tinytex())                       \
+"
+
+# main
+git clone https://github.com/mhunter1/dynr.git
+cd dynr
+GHSHA=`git rev-parse origin/master`
+GHSHAMSG="This release is based on the $GHSHA commit in the master branch."
+./configure
+make clean install
+cd ..
+rm -rf dynr
+
+# Directories
+DEFAULT_USER=${DEFAULT_USER:-"rstudio"}
+
+## working directory folder
+mkdir -p /home/${DEFAULT_USER}/working-dir
+cd /home/${DEFAULT_USER}/working-dir
+wget https://raw.githubusercontent.com/jeksterslab/template/main/project.Rproj
+echo "session-default-working-dir=/home/${DEFAULT_USER}/working-dir" >> /etc/rstudio/rsession.conf
+chown -R "${DEFAULT_USER}:${DEFAULT_USER}" "/home/${DEFAULT_USER}/working-dir"
+
+## project folder
+mkdir -p /home/${DEFAULT_USER}/project-dir
+cd /home/${DEFAULT_USER}/project-dir
+echo "session-default-new-project-dir=/home/${DEFAULT_USER}/project-dir" >> /etc/rstudio/rsession.conf
+chown -R "${DEFAULT_USER}:${DEFAULT_USER}" "/home/${DEFAULT_USER}/project-dir"
+
+## GitHub SHA
+mkdir -p /home/rstudio/project-dir
+cd /home/rstudio/project-dir
+touch .GHSHA
+touch .GHSHAMSG
+echo "$GHSHA" > .GHSHA
+echo "$GHSHAMSG" > .GHSHAMSG
+chown -R "${DEFAULT_USER}:${DEFAULT_USER}" "/home/rstudio/project-dir"
+
+# Clean up
+rm -rf /var/lib/apt/lists/*
+rm -rf /tmp/downloaded_packages
+
+## Strip binary installed libraries from RSPM
+## https://github.com/rocker-org/rocker-versioned2/issues/340
+strip /usr/local/lib/R/site-library/*/libs/*.so
+
+# Installation information
+echo -e "Session information...\n"
+R -q -e "sessionInfo()"
+
+# Check dynr
+echo -e "Check the dynr package...\n"
+R -q -e "library(dynr)"
+R -e "demo('LinearSDE', package = 'dynr')"
+cat -e "\n/home/rstudio/project-dir/.GHSHAMSG"
+echo -e "\nInstall dynr package, done!"
